export interface IconSet {
  name: string;
  display: string;
  icons: Partial<Record<string, string>>;
}

export const set: IconSet = {
  name: 'lucide-icons',
  display: 'Lucide',
  icons: {
    'codicon:account': 'lucide:user',
    // 'codicon:activate-breakpoints': 'lucide:activate-breakpoints',
    'codicon:add': 'lucide:plus',
    'codicon:archive': 'lucide:archive',
    'codicon:arrow-both': 'lucide:move-horizontal',
    'codicon:arrow-circle-down': 'lucide:circle-arrow-down',
    'codicon:arrow-circle-left': 'lucide:circle-arrow-left',
    'codicon:arrow-circle-right': 'lucide:circle-arrow-right',
    'codicon:arrow-circle-up': 'lucide:circle-arrow-up',
    'codicon:arrow-down': 'lucide:arrow-down',
    'codicon:arrow-left': 'lucide:arrow-left',
    'codicon:arrow-right': 'lucide:arrow-right',
    'codicon:arrow-small-down': 'lucide:move-down',
    'codicon:arrow-small-left': 'lucide:arrow-move-left',
    'codicon:arrow-small-right': 'lucide:arrow-narrow-right',
    'codicon:arrow-small-up': 'lucide:move-left',
    'codicon:arrow-swap': 'lucide:arrow-right-left',
    'codicon:arrow-up': 'lucide:arrow-up',
    'codicon:beaker': 'lucide:flask-conical',
    // 'codicon:azure-devops': 'lucide:azure-devops',
    // 'codicon:azure': 'lucide:brand-azure',
    'codicon:beaker-stop': 'lucide:flask-conical-off',
    'codicon:bell': 'lucide:bell',
    'codicon:bell-dot': 'lucide:bell-dot',
    // 'codicon:bell-slash-dot': 'lucide:bell-slash-dot',
    'codicon:bell-slash': 'lucide:bell-off',
    // 'codicon:blank': 'lucide:blank',
    'codicon:bold': 'lucide:bold',
    'codicon:book': 'lucide:book',
    'codicon:bookmark': 'lucide:bookmark',
    'codicon:bracket': 'lucide:braces',
    // 'codicon:bracket-dot': 'lucide:bracket-dot',
    // 'codicon:bracket-error': 'lucide:braces-off',
    'codicon:briefcase': 'lucide:briefcase',
    'codicon:broadcast': 'lucide:podcast',
    'codicon:browser': 'lucide:app-window',
    'codicon:bug': 'lucide:bug',
    'codicon:calendar': 'lucide:calendar',
    'codicon:call-incoming': 'lucide:phone-incoming',
    'codicon:call-outgoing': 'lucide:phone-outgoing',
    'codicon:case-sensitive': 'lucide:a-large-small',
    'codicon:check': 'lucide:check',
    'codicon:check-all': 'lucide:check-check',
    'codicon:checklist': 'lucide:list-check',
    'codicon:chevron-down': 'lucide:chevron-down',
    'codicon:chevron-left': 'lucide:chevron-left',
    'codicon:chevron-right': 'lucide:chevron-right',
    // 'codicon:circle-small-filled': 'lucide:circle-small-filled',
    // 'codicon:circle-small': 'lucide:circle-small',
    // 'codicon:circle': 'lucide:point',
    'codicon:chevron-up': 'lucide:chevron-up',
    // 'codicon:chrome-close': 'lucide:chrome-close',
    // 'codicon:chrome-maximize': 'lucide:chrome-maximize',
    // 'codicon:chrome-minimize': 'lucide:chrome-minimize',
    // 'codicon:chrome-restore': 'lucide:chrome-restore',
    'codicon:clock': 'lucide:clock',
    // 'codicon:circle-filled': 'lucide:point-filled',
    'codicon:circle-large': 'lucide:circle',
    // 'codicon:circle-large-filled': 'lucide:circle-filled',
    'codicon:circle-slash': 'lucide:circle-off',
    'codicon:circuit-board': 'lucide:circuit-board',
    'codicon:clear-all': 'lucide:list-x',
    // 'codicon:clippy': 'lucide:clippy',
    'codicon:close-all': 'lucide:copy-x',
    'codicon:close': 'lucide:x',
    'codicon:cloud': 'lucide:cloud',
    'codicon:cloud-download': 'lucide:cloud-download',
    'codicon:cloud-upload': 'lucide:cloud-upload',
    'codicon:code': 'lucide:code',
    'codicon:comment': 'lucide:message-square',
    'codicon:code-review': 'lucide:message-square-code',
    'codicon:compare-changes': 'lucide:git-compare-arrows',
    'codicon:collapse-all': 'lucide:copy-minus',
    // 'codicon:collapse-close-all': 'lucide:library-close',
    'codicon:color-mode': 'lucide:contrast',
    'codicon:combine': 'lucide:combine',
    'codicon:comment-discussion': 'lucide:messages-square',
    'codicon:comment-draft': 'lucide:message-square-dashed',
    'codicon:comment-unresolved': 'lucide:message-square-dot',
    'codicon:compass': 'lucide:compass',
    // 'codicon:compass-active': 'lucide:compass-active',
    // 'codicon:compass-dot': 'lucide:compass-dot',
    'codicon:copy': 'lucide:copy',
    'codicon:credit-card': 'lucide:credit-card',
    'codicon:dash': 'lucide:minus',
    'codicon:dashboard': 'lucide:gauge',
    'codicon:database': 'lucide:database',
    'codicon:debug': 'lucide:bug',
    'codicon:debug-all': 'lucide:debug-all',
    'codicon:debug-alt': 'lucide:bug-play',
    'codicon:debug-alt-small': 'lucide:bug-play',
    'codicon:debug-breakpoint-conditional': 'lucide:debug-breakpoint-conditional',
    'codicon:debug-breakpoint-conditional-unverified': 'lucide:debug-breakpoint-conditional-unverified',
    'codicon:debug-breakpoint-data': 'lucide:debug-breakpoint-data',
    'codicon:debug-breakpoint-data-unverified': 'lucide:debug-breakpoint-data-unverified',
    'codicon:debug-breakpoint-function': 'lucide:debug-breakpoint-function',
    'codicon:debug-breakpoint-function-unverified': 'lucide:debug-breakpoint-function-unverified',
    'codicon:debug-breakpoint-log': 'lucide:debug-breakpoint-log',
    'codicon:debug-breakpoint-log-unverified': 'lucide:debug-breakpoint-log-unverified',
    'codicon:debug-breakpoint-unsupported': 'lucide:debug-breakpoint-unsupported',
    'codicon:debug-console': 'lucide:debug-console',
    'codicon:debug-continue': 'lucide:debug-continue',
    'codicon:debug-continue-small': 'lucide:debug-continue-small',
    'codicon:debug-coverage': 'lucide:debug-coverage',
    'codicon:debug-disconnect': 'lucide:unplug',
    'codicon:debug-line-by-line': 'lucide:list-video',
    'codicon:debug-pause': 'lucide:pause',
    'codicon:debug-rerun': 'lucide:debug-rerun',
    'codicon:debug-restart': 'lucide:rotate-ccw',
    'codicon:debug-restart-frame': 'lucide:list-restart',
    'codicon:debug-reverse-continue': 'lucide:debug-reverse-continue',
    'codicon:debug-stackframe': 'lucide:debug-stackframe',
    'codicon:debug-stackframe-active': 'lucide:debug-stackframe-active',
    'codicon:debug-start': 'lucide:play',
    'codicon:debug-step-back': 'lucide:undo-dot',
    'codicon:debug-step-into': 'lucide:arrow-down-to-dot',
    'codicon:debug-step-out': 'lucide:arrow-up-from-dot',
    'codicon:debug-step-over': 'lucide:redo-dot',
    'codicon:debug-stop': 'lucide:square',
    'codicon:desktop-download': 'lucide:monitor-down',
    'codicon:device-camera': 'lucide:camera',
    'codicon:device-camera-video': 'lucide:video',
    'codicon:device-mobile': 'lucide:smartphone',
    // 'codicon:diff': 'lucide:diff',
    'codicon:diff-added': 'lucide:square-plus',
    'codicon:diff-ignored': 'lucide:square-slash',
    'codicon:diff-modified': 'lucide:square-dot',
    'codicon:diff-multiple': 'lucide:file-diff',
    'codicon:diff-removed': 'lucide:square-divide',
    'codicon:diff-renamed': 'lucide:square-arrow-right',
    'codicon:discard': 'lucide:undo-2',
    'codicon:drop-down-button': 'lucide:chevron-down',
    'codicon:edit': 'lucide:pencil',
    'codicon:editor-layout': 'lucide:layout-panel-left',
    'codicon:ellipsis': 'lucide:ellipsis',
    'codicon:empty-window': 'lucide:empty-window',
    'codicon:error': 'lucide:circle-x',
    'codicon:error-small': 'lucide:circle-x',
    'codicon:exclude': 'lucide:exclude',
    'codicon:expand-all': 'lucide:copy-plus',
    'codicon:export': 'lucide:arrow-right-from-line',
    'codicon:extensions': 'lucide:blocks',
    'codicon:eye': 'lucide:eye',
    'codicon:eye-closed': 'lucide:eye-off',
    'codicon:feedback': 'lucide:feedback',
    'codicon:file': 'lucide:file',
    'codicon:file-binary': 'lucide:file-digit',
    'codicon:file-code': 'lucide:file-code',
    'codicon:file-media': 'lucide:file-image',
    'codicon:file-pdf': 'lucide:file-type',
    'codicon:file-submodule': 'lucide:folders',
    'codicon:file-symlink-directory': 'lucide:folder-symlink',
    'codicon:file-symlink-file': 'lucide:file-symlink',
    'codicon:file-zip': 'lucide:file-archive',
    'codicon:files': 'lucide:folder',
    'codicon:filter': 'lucide:filter',
    'codicon:preferences-filter': 'lucide:filter',
    'codicon:filter-filled': 'lucide:filter-filled',
    'codicon:find-selection': 'lucide:align-left',
    'codicon:flame': 'lucide:flame',
    'codicon:fold': 'lucide:chevrons-down-up',
    'codicon:fold-down': 'lucide:chevrons-down',
    'codicon:fold-up': 'lucide:chevrons-up',
    'codicon:folder': 'lucide:folder-closed',
    'codicon:folder-active': 'lucide:folder-check',
    'codicon:folder-library': 'lucide:library',
    'codicon:folder-opened': 'lucide:folder-open',
    'codicon:gear': 'lucide:settings',
    'codicon:gift': 'lucide:gift',
    'codicon:gist-secret': 'lucide:file-lock-2',
    'codicon:git-branch': 'lucide:git-branch',
    'codicon:git-commit': 'lucide:git-commit-vertical',
    'codicon:git-compare': 'lucide:git-compare',
    'codicon:git-merge': 'lucide:git-merge',
    'codicon:git-pull-request': 'lucide:git-pull-request',
    'codicon:git-pull-request-closed': 'lucide:git-pull-request-closed',
    'codicon:git-pull-request-create': 'lucide:git-pull-request-create',
    'codicon:git-pull-request-draft': 'lucide:git-pull-request-draft',
    'codicon:git-pull-request-go-to-changes': 'lucide:git-pull-request-go-to-changes',
    'codicon:git-pull-request-new-changes': 'lucide:file-diff',
    'codicon:github': 'lucide:github',
    // 'codicon:github-action': 'lucide:circle-play',
    'codicon:github-alt': 'lucide:github',
    'codicon:github-inverted': 'lucide:github',
    'codicon:gitlens-gitlens': 'lucide:git-merge',
    'codicon:gitlens-gitlens-inspect': 'lucide:git-merge',
    'codicon:gitlens-switch': 'lucide:switch',
    'codicon:globe': 'lucide:globe',
    'codicon:go-to-file': 'lucide:file-symlink',
    'codicon:grabber': 'lucide:grip-horizontal',
    'codicon:graph': 'lucide:bar-chart-big',
    // 'codicon:graph-left': 'lucide:graph-left',
    'codicon:graph-line': 'lucide:chart-line',
    'codicon:graph-scatter': 'lucide:chart-scatter',
    'codicon:gripper': 'lucide:grip-vertical',
    // 'codicon:group-by-ref-type': 'lucide:group-by-ref-type',
    'codicon:heart': 'lucide:heart',
    'codicon:heart-filled': 'lucide:heart-filled',
    'codicon:history': 'lucide:history',
    'codicon:home': 'lucide:house',
    // 'codicon:horizontal-rule': 'lucide:horizontal-rule',
    'codicon:hubot': 'lucide:bot-message-square',
    'codicon:inbox': 'lucide:inbox',
    'codicon:indent': 'lucide:corner-down-right',
    'codicon:info': 'lucide:info',
    'codicon:insert': 'lucide:between-horizontal-start',
    'codicon:inspect': 'lucide:square-mouse-pointer',
    'codicon:issue-draft': 'lucide:circle-dot-dashed',
    'codicon:issue-reopened': 'lucide:refresh-ccw-dot',
    'codicon:issues': 'lucide:circle-dot',
    'codicon:italic': 'lucide:italic',
    'codicon:jersey': 'lucide:shirt',
    'codicon:json': 'lucide:braces',
    'codicon:kebab-vertical': 'lucide:ellipsis-vertical',
    'codicon:key': 'lucide:key',
    'codicon:law': 'lucide:scale',
    'codicon:layers': 'lucide:layers',
    'codicon:layers-active': 'lucide:layers-active',
    'codicon:layers-dot': 'lucide:layers-dot',
    'codicon:layout': 'lucide:layout-panel-left',
    // 'codicon:layout-activitybar-left': 'lucide:layout-sidebar',
    // 'codicon:layout-activitybar-right': 'lucide:layout-sidebar-right',
    // 'codicon:layout-centered': 'lucide:layout-centered',
    // 'codicon:layout-menubar': 'lucide:layout-menubar',
    // 'codicon:layout-panel': 'lucide:layout-bottombar-collapse-filled',
    // 'codicon:layout-panel-center': 'lucide:layout-panel-center',
    // 'codicon:layout-panel-justify': 'lucide:layout-panel-justify',
    // 'codicon:layout-panel-left': 'lucide:layout-panel-left',
    // 'codicon:layout-panel-off': 'lucide:layout-bottombar-expand-filled',
    // 'codicon:layout-panel-right': 'lucide:layout-panel-right',
    // 'codicon:layout-sidebar-left': 'lucide:layout-sidebar-left-collapse-filled',
    // 'codicon:layout-sidebar-left-off': 'lucide:layout-sidebar-left-expand-filled',
    // 'codicon:layout-sidebar-right': 'lucide:layout-sidebar-right-collapse-filled',
    // 'codicon:layout-sidebar-right-off': 'lucide:layout-sidebar-right-expand-filled',
    // 'codicon:layout-statusbar': 'lucide:layout-bottombar-filled',
    'codicon:library': 'lucide:library',
    'codicon:lightbulb': 'lucide:lightbulb',
    'codicon:light-bulb': 'lucide:lightbulb',
    'codicon:lightbulb-sparkle': 'lucide:sparkles',
    'codicon:lightbulb-autofix': 'lucide:lightbulb',
    'codicon:link': 'lucide:link',
    'codicon:link-external': 'lucide:external-link',
    'codicon:list-filter': 'lucide:list-filter',
    'codicon:list-flat': 'lucide:list',
    'codicon:list-ordered': 'lucide:list-ordered',
    'codicon:list-selection': 'lucide:align-left',
    'codicon:list-tree': 'lucide:list-tree',
    'codicon:list-unordered': 'lucide:list',
    'codicon:live-share': 'lucide:live-share',
    'codicon:loading': 'lucide:loader-circle',
    'codicon:location': 'lucide:map-pin',
    'codicon:lock': 'lucide:lock',
    // 'codicon:lock-small': 'lucide:lock-small',
    'codicon:magnet': 'lucide:magnet',
    'codicon:mail': 'lucide:mail',
    'codicon:mail-read': 'lucide:mail-open',
    'codicon:map': 'lucide:map',
    // 'codicon:map-filled': 'lucide:map-filled',
    'codicon:markdown': 'lucide:markdown',
    'codicon:megaphone': 'lucide:megaphone',
    'codicon:mention': 'lucide:at-sign',
    'codicon:menu': 'lucide:menu',
    'codicon:merge': 'lucide:merge',
    'codicon:milestone': 'lucide:signpost',
    'codicon:mirror': 'lucide:mirror',
    'codicon:more': 'lucide:dots',
    'codicon:mortar-board': 'lucide:school',
    'codicon:move': 'lucide:move',
    'codicon:multiple-windows': 'lucide:multiple-windows',
    'codicon:mute': 'lucide:volume-off',
    'codicon:new-file': 'lucide:file-plus',
    'codicon:new-folder': 'lucide:folder-plus',
    'codicon:newline': 'lucide:corner-down-left',
    'codicon:no-newline': 'lucide:no-newline',
    'codicon:note': 'lucide:notebook-text',
    'codicon:notebook': 'lucide:notebook',
    'codicon:notebook-template': 'lucide:notebook-template',
    // 'codicon:octoface': 'lucide:octoface',
    'codicon:open-preview': 'lucide:scan-eye',
    'codicon:organization': 'lucide:users',
    'codicon:output': 'lucide:notepad-text',
    'codicon:package': 'lucide:package',
    'codicon:paintcan': 'lucide:paint-bucket',
    'codicon:panel-close': 'lucide:x',
    'codicon:pass': 'lucide:circle-check',
    'codicon:pass-filled': 'lucide:circle-check-filled',
    'codicon:person': 'lucide:user',
    'codicon:person-add': 'lucide:user-plus',
    'codicon:pie-chart': 'lucide:chart-pie',
    'codicon:pin': 'lucide:pin',
    'codicon:pinned': 'lucide:pin',
    'codicon:pinned-dirty': 'lucide:pinned-dirty',
    'codicon:play': 'lucide:play',
    'codicon:play-circle': 'lucide:circle-play',
    'codicon:plug': 'lucide:plug',
    'codicon:plus': 'lucide:plus',
    'codicon:ports-stop-forward-icon': 'lucide:x',
    'codicon:preserve-case': 'lucide:case-upper',
    'codicon:preview': 'lucide:newspaper',
    'codicon:primitive-square': 'lucide:square',
    'codicon:project': 'lucide:square-kanban',
    'codicon:pulse': 'lucide:activity',
    'codicon:question': 'lucide:circle-help',
    'codicon:quick-input-back': 'lucide:arrow-left',
    'codicon:quote': 'lucide:quote',
    'codicon:radio-tower': 'lucide:radio-tower',
    'codicon:reactions': 'lucide:smile-plus',
    'codicon:record': 'lucide:circle-dot',
    'codicon:record-keys': 'lucide:keyboard',
    'codicon:record-small': 'lucide:record-small',
    'codicon:redo': 'lucide:redo-2',
    'codicon:references': 'lucide:references',
    'codicon:refresh': 'lucide:refresh-ccw',
    'codicon:regex': 'lucide:regex',
    'codicon:remote': 'lucide:server',
    'codicon:remote-explorer': 'lucide:screen-share',
    'codicon:remove': 'lucide:minus',
    'codicon:replace': 'lucide:replace',
    'codicon:replace-all': 'lucide:replace-all',
    'codicon:reply': 'lucide:undo-2',
    'codicon:repo': 'lucide:book-marked',
    'codicon:repo-clone': 'lucide:book-copy',
    'codicon:repo-force-push': 'lucide:repo-force-push',
    'codicon:repo-forked': 'lucide:git-fork',
    'codicon:repo-pull': 'lucide:repo-pull',
    'codicon:repo-push': 'lucide:book-upload',
    'codicon:report': 'lucide:message-square-warning',
    'codicon:request-changes': 'lucide:file-diff',
    'codicon:rocket': 'lucide:rocket',
    'codicon:root-folder': 'lucide:folder-root',
    'codicon:root-folder-opened': 'lucide:folder-root',
    'codicon:rss': 'lucide:rss',
    'codicon:ruby': 'lucide:gem',
    'codicon:run-above': 'lucide:run-above',
    'codicon:run-all': 'lucide:run-all',
    'codicon:run-below': 'lucide:run-below',
    'codicon:run-errors': 'lucide:run-errors',
    'codicon:save': 'lucide:save',
    'codicon:save-all': 'lucide:save-all',
    'codicon:save-as': 'lucide:save',
    'codicon:screen-full': 'lucide:maximize',
    'codicon:screen-normal': 'lucide:minimize',
    'codicon:search': 'lucide:search',
    'codicon:search-fuzzy': 'lucide:search-slash',
    'codicon:search-stop': 'lucide:search-x',
    'codicon:send': 'lucide:send',
    'codicon:server': 'lucide:server',
    'codicon:server-environment': 'lucide:server-environment',
    'codicon:server-process': 'lucide:server-process',
    'codicon:settings': 'lucide:settings-2',
    'codicon:settings-gear': 'lucide:settings',
    'codicon:shield': 'lucide:shield',
    'codicon:sign-in': 'lucide:log-in',
    'codicon:sign-out': 'lucide:log-out',
    'codicon:smiley': 'lucide:smile',
    'codicon:sort-precedence': 'lucide:sort-precedence',
    'codicon:source-control': 'lucide:git-branch',
    'codicon:sparkle': 'lucide:sparkles',
    'codicon:split-horizontal': 'lucide:columns-2',
    'codicon:split-vertical': 'lucide:rows-2',
    'codicon:squirrel': 'lucide:squirrel',
    'codicon:star-empty': 'lucide:star',
    'codicon:star-full': 'lucide:star-filled',
    'codicon:star-half': 'lucide:star-half-filled',
    'codicon:stop-circle': 'lucide:circle-stop',
    'codicon:symbol-array': 'lucide:brackets',
    'codicon:symbol-boolean': 'lucide:toggle-left',
    'codicon:symbol-class': 'lucide:circuit-board',
    'codicon:symbol-color': 'lucide:palette',
    'codicon:symbol-constant': 'lucide:square-menu',
    'codicon:symbol-enum': 'lucide:square-chart-gantt',
    'codicon:symbol-enum-member': 'lucide:square-chart-gantt',
    'codicon:symbol-event': 'lucide:zap',
    'codicon:symbol-field': 'lucide:cuboid',
    'codicon:symbol-file': 'lucide:file',
    'codicon:symbol-interface': 'lucide:git-commit-horizontal',
    'codicon:symbol-key': 'lucide:case-sensitive',
    'codicon:symbol-keyword': 'lucide:letter-text',
    'codicon:symbol-method': 'lucide:box',
    'codicon:symbol-misc': 'lucide:square-asterisk',
    'codicon:symbol-namespace': 'lucide:braces',
    'codicon:symbol-module': 'lucide:braces',
    'codicon:symbol-numeric': 'lucide:sigma',
    'codicon:symbol-operator': 'lucide:divide',
    'codicon:symbol-parameter': 'lucide:scan-text',
    'codicon:symbol-property': 'lucide:wrench',
    'codicon:symbol-ruler': 'lucide:ruler',
    'codicon:symbol-snippet': 'lucide:square-dashed-bottom',
    'codicon:symbol-string': 'lucide:whole-word',
    'codicon:symbol-text': 'lucide:case-upper',
    'codicon:symbol-structure': 'lucide:layout-dashboard',
    'codicon:symbol-struct': 'lucide:layout-dashboard',
    'codicon:symbol-variable': 'lucide:variable',
    'codicon:symbol-function': 'lucide:square-function',
    'codicon:sync': 'lucide:refresh-ccw',
    'codicon:sync-ignored': 'lucide:refresh-cw-off',
    'codicon:table': 'lucide:table',
    'codicon:tag': 'lucide:tag',
    'codicon:target': 'lucide:target',
    'codicon:tasklist': 'lucide:list-check',
    'codicon:telescope': 'lucide:telescope',
    'codicon:terminal': 'lucide:terminal',
    'codicon:terminal-bash': 'lucide:square-terminal',
    'codicon:terminal-cmd': 'lucide:square-terminal',
    // 'codicon:terminal-debian': 'lucide:brand-debian',
    // 'codicon:terminal-linux': 'lucide:terminal-linux',
    'codicon:terminal-powershell': 'lucide:square-terminal',
    'codicon:terminal-tmux': 'lucide:layout-panel-left',
    // 'codicon:terminal-ubuntu': 'lucide:brand-ubuntu',
    'codicon:text-size': 'lucide:a-large-small',
    'codicon:three-bars': 'lucide:menu',
    'codicon:thumbsdown': 'lucide:thumbs-down',
    'codicon:thumbsup': 'lucide:thumbs-up',
    'codicon:tools': 'lucide:wrench',
    'codicon:toolbar-more': 'lucide:ellipsis',
    'codicon:trash': 'lucide:trash-2',
    'codicon:trashcan': 'lucide:trash-2',
    'codicon:tree-item-expanded': 'lucide:chevron-down',
    'codicon:triangle-down': 'lucide:caret-down-filled',
    'codicon:triangle-left': 'lucide:caret-left-filled',
    'codicon:triangle-right': 'lucide:caret-right-filled',
    'codicon:triangle-up': 'lucide:caret-up-filled',
    'codicon:twitter': 'lucide:twitter',
    // 'codicon:type-hierarchy': 'lucide:type-hierarchy',
    // 'codicon:type-hierarchy-sub': 'lucide:type-hierarchy-sub',
    // 'codicon:type-hierarchy-super': 'lucide:type-hierarchy-super',
    // 'codicon:unfold': 'lucide:unfold',
    // 'codicon:ungroup-by-ref-type': 'lucide:ungroup-by-ref-type',
    'codicon:unlock': 'lucide:lock-open',
    'codicon:unmute': 'lucide:volume',
    'codicon:unverified': 'lucide:badge-help',
    'codicon:variable-group': 'lucide:variable',
    'codicon:verified': 'lucide:badge-check',
    'codicon:verified-filled': 'lucide:badge-check',
    'codicon:versions': 'lucide:gallery-horizontal-end',
    'codicon:vm': 'lucide:monitor',
    'codicon:vm-active': 'lucide:monitor-check',
    'codicon:vm-connect': 'lucide:screen-share',
    'codicon:vm-outline': 'lucide:monitor-dot',
    'codicon:vm-running': 'lucide:monitor-play',
    'codicon:wand': 'lucide:wand',
    'codicon:warning': 'lucide:triangle-alert',
    'codicon:watch': 'lucide:watch',
    'codicon:whitespace': 'lucide:pilcrow',
    'codicon:whole-word': 'lucide:whole-word',
    'codicon:widget-close': 'lucide:x',
    'codicon:window': 'lucide:app-window-mac',
    'codicon:word-wrap': 'lucide:wrap-text',
    'codicon:workspace-trusted': 'lucide:shield-check',
    'codicon:workspace-unknown': 'lucide:shield-question',
    'codicon:workspace-untrusted': 'lucide:shield-x',
    'codicon:zoom-in': 'lucide:zoom-in',
    'codicon:zoom-out': 'lucide:zoom-out',
    'codicon:copilot': 'lucide:bot',
    'codicon:mic': 'lucide:mic',
    'codicon:attach': 'lucide:paperclip',
  },
};
